kind: ConfigMap
apiVersion: v1
metadata:
  name: -nginx-configmap
data:
  nginx.conf: |
        server {
                listen       80;
                root   /var/appfiles/;
                index index.php index.html index.htm;
   

                # Logs
                access_log /var/log/nginx/tcc-webapp-access.log;
                error_log /var/log/nginx/tcc-webapp-error.log;

                location / {
                    # try_files $uri $uri/ =404;
                    # try_files $uri $uri/ /index.php?q=$uri&$args;
                        try_files $uri $uri/ /index.php?$query_string;
                }


                location ~ \.php$ {
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass 127.0.0.1:9000;
                        fastcgi_index index.php;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        include fastcgi_params;
                }
        }
        
    