apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
#   - name: -configmap

resources:
  # - resources/namespace.yaml
  - resources/service.yaml
  - resources/nginx-configmap.yaml
  - resources/deployment.yaml
  - resources/ingress.yaml

namespace: cloudcommunity

images:
  - name: DONTTOUCH-replace-me-kustomization # match images with this name
    newTag: $IMAGE_TAG # override the tag
    newName: $IMAGE_URI
